const DASHBOARD_HTML_LINES = [
  '<!doctype html>',
  '<html lang="en">',
  '  <head>',
  '    <meta charset="utf-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '    <title>My Pi Dashboard</title>',
  '    <style>',
  '      :root {',
  '        color-scheme: dark;',
  '        --bg: #0b1020;',
  '        --panel: #111830;',
  '        --panel-2: #16203f;',
  '        --text: #ecf3ff;',
  '        --muted: #9fb0d0;',
  '        --accent: #6ea8fe;',
  '        --accent-2: #7ef0c5;',
  '        --danger: #ff7b7b;',
  '        --warning: #ffd479;',
  '        --border: rgba(255,255,255,0.1);',
  '        --shadow: 0 12px 30px rgba(0,0,0,0.25);',
  '      }',
  '',
  '      * { box-sizing: border-box; }',
  '      body {',
  '        margin: 0;',
  '        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
  '        background: linear-gradient(180deg, #0a0f1d 0%, #0e1730 100%);',
  '        color: var(--text);',
  '      }',
  '',
  '      .wrap {',
  '        width: min(1400px, calc(100vw - 32px));',
  '        margin: 24px auto 48px;',
  '      }',
  '',
  '      .hidden { display: none !important; }',
  '      .row { display: flex; gap: 12px; flex-wrap: wrap; }',
  '      .grow { flex: 1 1 300px; }',
  '',
  '      .card {',
  '        background: rgba(17, 24, 48, 0.92);',
  '        border: 1px solid var(--border);',
  '        border-radius: 18px;',
  '        padding: 18px;',
  '        box-shadow: var(--shadow);',
  '        backdrop-filter: blur(8px);',
  '      }',
  '',
  '      h1, h2, h3 { margin: 0 0 12px; }',
  '      h1 { font-size: 28px; }',
  '      h2 { font-size: 20px; }',
  '      h3 { font-size: 16px; }',
  '      p, li, td, th, label, input, select, button { font-size: 14px; }',
  '      .muted { color: var(--muted); }',
  '      .small { font-size: 12px; color: var(--muted); }',
  '',
  '      .hero {',
  '        display: flex;',
  '        justify-content: space-between;',
  '        align-items: flex-start;',
  '        gap: 16px;',
  '        margin-bottom: 18px;',
  '      }',
  '',
  '      .hero-actions { display: flex; gap: 10px; flex-wrap: wrap; }',
  '',
  '      button {',
  '        border: 0;',
  '        border-radius: 12px;',
  '        padding: 11px 14px;',
  '        cursor: pointer;',
  '        color: var(--text);',
  '        background: linear-gradient(180deg, #3a6eea 0%, #2851bf 100%);',
  '        font-weight: 600;',
  '      }',
  '',
  '      button.secondary {',
  '        background: #223055;',
  '      }',
  '',
  '      button.danger {',
  '        background: linear-gradient(180deg, #c34e4e 0%, #9f3e3e 100%);',
  '      }',
  '',
  '      button.small {',
  '        padding: 8px 10px;',
  '        font-size: 12px;',
  '      }',
  '',
  '      button:disabled {',
  '        opacity: 0.6;',
  '        cursor: wait;',
  '      }',
  '',
  '      input, select {',
  '        width: 100%;',
  '        padding: 11px 12px;',
  '        border-radius: 12px;',
  '        border: 1px solid var(--border);',
  '        background: #0f1730;',
  '        color: var(--text);',
  '      }',
  '',
  '      form .field {',
  '        display: grid;',
  '        gap: 6px;',
  '      }',
  '',
  '      .grid {',
  '        display: grid;',
  '        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));',
  '        gap: 12px;',
  '      }',
  '',
  '      .stat {',
  '        background: rgba(255,255,255,0.02);',
  '        border: 1px solid var(--border);',
  '        border-radius: 16px;',
  '        padding: 16px;',
  '      }',
  '',
  '      .stat .label {',
  '        color: var(--muted);',
  '        font-size: 12px;',
  '        text-transform: uppercase;',
  '        letter-spacing: 0.08em;',
  '      }',
  '',
  '      .stat .value {',
  '        margin-top: 8px;',
  '        font-size: 24px;',
  '        font-weight: 700;',
  '      }',
  '',
  '      table {',
  '        width: 100%;',
  '        border-collapse: collapse;',
  '        margin-top: 8px;',
  '      }',
  '',
  '      th, td {',
  '        text-align: left;',
  '        padding: 10px 8px;',
  '        border-bottom: 1px solid rgba(255,255,255,0.08);',
  '        vertical-align: top;',
  '      }',
  '',
  '      code, pre {',
  '        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;',
  '      }',
  '',
  '      pre {',
  '        white-space: pre-wrap;',
  '        overflow-wrap: anywhere;',
  '        margin: 0;',
  '        background: #0c1327;',
  '        border: 1px solid var(--border);',
  '        border-radius: 12px;',
  '        padding: 12px;',
  '      }',
  '',
  '      .pill {',
  '        display: inline-block;',
  '        padding: 4px 8px;',
  '        border-radius: 999px;',
  '        background: rgba(110, 168, 254, 0.16);',
  '        color: #b9d2ff;',
  '        font-size: 12px;',
  '        margin-right: 6px;',
  '        margin-bottom: 6px;',
  '      }',
  '',
  '      .pill.good { background: rgba(126, 240, 197, 0.16); color: #b6ffe7; }',
  '      .pill.warn { background: rgba(255, 212, 121, 0.16); color: #ffe7ab; }',
  '      .pill.bad { background: rgba(255, 123, 123, 0.16); color: #ffc1c1; }',
  '',
  '      .banner {',
  '        margin-top: 12px;',
  '        padding: 12px 14px;',
  '        border-radius: 12px;',
  '        border: 1px solid var(--border);',
  '        background: rgba(255,255,255,0.04);',
  '      }',
  '',
  '      .banner.error {',
  '        border-color: rgba(255,123,123,0.5);',
  '        background: rgba(255,123,123,0.1);',
  '      }',
  '',
  '      .banner.success {',
  '        border-color: rgba(126,240,197,0.45);',
  '        background: rgba(126,240,197,0.12);',
  '      }',
  '',
  '      #login-panel {',
  '        max-width: 480px;',
  '        margin: 10vh auto 0;',
  '      }',
  '',
  '      .section { margin-top: 18px; }',
  '      .section-header {',
  '        display: flex;',
  '        justify-content: space-between;',
  '        align-items: center;',
  '        gap: 12px;',
  '        margin-bottom: 8px;',
  '      }',
  '',
  '      .list {',
  '        display: grid;',
  '        gap: 10px;',
  '      }',
  '',
  '      .item {',
  '        padding: 12px;',
  '        border-radius: 12px;',
  '        border: 1px solid rgba(255,255,255,0.08);',
  '        background: rgba(255,255,255,0.03);',
  '      }',
  '',
  '      .item-title {',
  '        font-weight: 700;',
  '        margin-bottom: 6px;',
  '      }',
  '',
  '      .source-item-header {',
  '        display: flex;',
  '        justify-content: space-between;',
  '        align-items: flex-start;',
  '        gap: 12px;',
  '      }',
  '',
  '      .source-actions {',
  '        display: flex;',
  '        gap: 8px;',
  '        flex-wrap: wrap;',
  '        justify-content: flex-end;',
  '      }',
  '',
  '      .logs {',
  '        display: grid;',
  '        gap: 8px;',
  '        max-height: 420px;',
  '        overflow: auto;',
  '      }',
  '',
  '      .log-entry {',
  '        border: 1px solid rgba(255,255,255,0.08);',
  '        border-left: 4px solid var(--accent);',
  '        border-radius: 12px;',
  '        background: #0c1327;',
  '        padding: 10px 12px;',
  '      }',
  '',
  '      .log-entry.warn { border-left-color: var(--warning); }',
  '      .log-entry.error { border-left-color: var(--danger); }',
  '',
  '      .log-meta {',
  '        display: flex;',
  '        justify-content: space-between;',
  '        gap: 10px;',
  '        margin-bottom: 6px;',
  '        color: var(--muted);',
  '        font-size: 12px;',
  '      }',
  '',
  '      .log-message {',
  '        white-space: pre-wrap;',
  '        overflow-wrap: anywhere;',
  '        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;',
  '        font-size: 12px;',
  '      }',
  '',
  '      .meta {',
  '        display: grid;',
  '        gap: 4px;',
  '        color: var(--muted);',
  '      }',
  '',
  '      @media (max-width: 720px) {',
  '        .wrap { width: min(100vw - 16px, 1400px); margin-top: 12px; }',
  '        .hero { flex-direction: column; }',
  '      }',
  '    </style>',
  '  </head>',
  '  <body>',
  '    <div class="wrap">',
  '      <section id="login-panel" class="card hidden">',
  '        <h1>My Pi Dashboard</h1>',
  '        <p class="muted">Enter your dashboard token to monitor Pi and manage my-pi scoped skills and extensions.</p>',
  '        <form id="login-form" class="section">',
  '          <div class="field">',
  '            <label for="token">Dashboard token</label>',
  '            <input id="token" name="token" type="password" autocomplete="current-password" placeholder="Enter token" required />',
  '          </div>',
  '          <div class="section">',
  '            <button type="submit">Unlock dashboard</button>',
  '          </div>',
  '        </form>',
  '        <div id="login-message" class="banner hidden"></div>',
  '      </section>',
  '',
  '      <main id="dashboard" class="hidden">',
  '        <div class="hero">',
  '          <div>',
  '            <h1>My Pi Dashboard</h1>',
  '            <p class="muted">Monitor runtime health, scheduled jobs, reminders, and my-pi scoped skills/extensions.</p>',
  '          </div>',
  '          <div class="hero-actions">',
  '            <button class="secondary" id="refresh-button">Refresh status</button>',
  '            <button class="secondary" id="reload-resources-button">Reload resources</button>',
  '            <button class="danger" id="logout-button">Logout</button>',
  '          </div>',
  '        </div>',
  '',
  '        <div id="flash" class="banner hidden"></div>',
  '',
  '        <section class="card section">',
  '          <div class="section-header">',
  '            <div>',
  '              <h2>Install into my-pi</h2>',
  '              <p class="small">Installs here are isolated to <code>~/.my-pi</code> / your configured my-pi agent dir, not the main Pi harness.</p>',
  '            </div>',
  '          </div>',
  '          <form id="install-form" class="row">',
  '            <div class="field grow">',
  '              <label for="install-kind">Install type</label>',
  '              <select id="install-kind" name="kind">',
  '                <option value="package">Package source (npm:, git:, URL, local package dir)</option>',
  '                <option value="skill-path">Skill path (local SKILL.md dir or skill file)</option>',
  '                <option value="extension-path">Extension path (local .ts/.js file or dir)</option>',
  '              </select>',
  '            </div>',
  '            <div class="field grow" style="min-width: 320px;">',
  '              <label for="install-source">Source</label>',
  '              <input id="install-source" name="source" placeholder="npm:@scope/pi-tools or /absolute/path/to/skill" required />',
  '            </div>',
  '            <div class="field" style="min-width: 180px; align-self: end;">',
  '              <button id="install-button" type="submit">Install</button>',
  '            </div>',
  '          </form>',
  '        </section>',
  '',
  '        <section class="section card">',
  '          <h2>Runtime overview</h2>',
  '          <div id="stats-grid" class="grid"></div>',
  '        </section>',
  '',
  '        <section class="section row">',
  '          <div class="card grow">',
  '            <div class="section-header">',
  '              <div>',
  '                <h2>Configured my-pi sources</h2>',
  '                <p class="small">These are the package/path entries stored in the my-pi agent config. You can update or remove them here.</p>',
  '              </div>',
  '            </div>',
  '            <div id="configured-sources" class="list"></div>',
  '          </div>',
  '          <div class="card grow">',
  '            <div class="section-header">',
  '              <div>',
  '                <h2>Active chats</h2>',
  '                <p class="small">Sessions are recycled automatically when resources change, while preserving SQLite history.</p>',
  '              </div>',
  '            </div>',
  '            <div id="active-chats"></div>',
  '          </div>',
  '        </section>',
  '',
  '        <section class="section row">',
  '          <div class="card grow">',
  '            <div class="section-header">',
  '              <div>',
  '                <h2>Installed extensions</h2>',
  '                <p class="small">Loaded from the my-pi agent dir and any configured external paths/packages.</p>',
  '              </div>',
  '            </div>',
  '            <div id="extensions-table"></div>',
  '          </div>',
  '          <div class="card grow">',
  '            <div class="section-header">',
  '              <div>',
  '                <h2>Installed skills</h2>',
  '                <p class="small">Shows skill descriptions, paths, and whether each resource is managed by my-pi.</p>',
  '              </div>',
  '            </div>',
  '            <div id="skills-table"></div>',
  '          </div>',
  '        </section>',
  '',
  '        <section class="section row">',
  '          <div class="card grow">',
  '            <h2>Cron jobs</h2>',
  '            <div id="cron-jobs"></div>',
  '          </div>',
  '          <div class="card grow">',
  '            <h2>Reminders</h2>',
  '            <div id="reminders"></div>',
  '          </div>',
  '        </section>',
  '',
  '        <section class="section row">',
  '          <div class="card grow">',
  '            <h2>Diagnostics</h2>',
  '            <div id="diagnostics"></div>',
  '          </div>',
  '          <div class="card grow">',
  '            <h2>Live logs</h2>',
  '            <p class="small">Server-sent events stream status and logs live without client polling.</p>',
  '            <div id="live-logs"></div>',
  '          </div>',
  '          <div class="card grow">',
  '            <h2>App details</h2>',
  '            <div id="app-details"></div>',
  '          </div>',
  '        </section>',
  '      </main>',
  '    </div>',
  '',
  '    <script>',
  '      const loginPanel = document.getElementById("login-panel");',
  '      const dashboard = document.getElementById("dashboard");',
  '      const loginForm = document.getElementById("login-form");',
  '      const loginMessage = document.getElementById("login-message");',
  '      const installForm = document.getElementById("install-form");',
  '      const installButton = document.getElementById("install-button");',
  '      const flash = document.getElementById("flash");',
  '      const refreshButton = document.getElementById("refresh-button");',
  '      const reloadResourcesButton = document.getElementById("reload-resources-button");',
  '      const logoutButton = document.getElementById("logout-button");',
  '      const statsGrid = document.getElementById("stats-grid");',
  '      const configuredSources = document.getElementById("configured-sources");',
  '      const activeChats = document.getElementById("active-chats");',
  '      const extensionsTable = document.getElementById("extensions-table");',
  '      const skillsTable = document.getElementById("skills-table");',
  '      const cronJobs = document.getElementById("cron-jobs");',
  '      const reminders = document.getElementById("reminders");',
  '      const diagnostics = document.getElementById("diagnostics");',
  '      const liveLogs = document.getElementById("live-logs");',
  '      const appDetails = document.getElementById("app-details");',
  '',
  '      let eventSource = null;',
  '      let currentLogs = [];',
  '',
  '      function escapeHtml(value) {',
  '        return String(value)',
  '          .replaceAll("&", "&amp;")',
  '          .replaceAll("<", "&lt;")',
  '          .replaceAll(">", "&gt;")',
  '          .replaceAll(\'"\', "&quot;")',
  '          .replaceAll("\'", "&#39;");',
  '      }',
  '',
  '      function formatDuration(seconds) {',
  '        const s = Number(seconds || 0);',
  '        const days = Math.floor(s / 86400);',
  '        const hours = Math.floor((s % 86400) / 3600);',
  '        const minutes = Math.floor((s % 3600) / 60);',
  '        const secs = s % 60;',
  '        const parts = [];',
  '        if (days) parts.push(`${days}d`);',
  '        if (hours || days) parts.push(`${hours}h`);',
  '        if (minutes || hours || days) parts.push(`${minutes}m`);',
  '        parts.push(`${secs}s`);',
  '        return parts.join(" ");',
  '      }',
  '',
  '      function badge(text, kind = "") {',
  '        return `<span class="pill ${kind}">${escapeHtml(text)}</span>`;',
  '      }',
  '',
  '      function code(value) {',
  '        return `<code>${escapeHtml(value)}</code>`;',
  '      }',
  '',
  '      function showBanner(message, kind = "") {',
  '        flash.className = `banner ${kind}`.trim();',
  '        flash.textContent = message;',
  '        flash.classList.remove("hidden");',
  '      }',
  '',
  '      function clearBanner() {',
  '        flash.className = "banner hidden";',
  '        flash.textContent = "";',
  '      }',
  '',
  '      async function api(path, options = {}) {',
  '        const response = await fetch(path, {',
  '          ...options,',
  '          headers: {',
  '            "Content-Type": "application/json",',
  '            ...(options.headers || {}),',
  '          },',
  '        });',
  '',
  '        if (response.status === 401) {',
  '          showLogin();',
  '          throw new Error("Authentication required.");',
  '        }',
  '',
  '        const payload = await response.json().catch(() => ({}));',
  '        if (!response.ok) {',
  '          throw new Error(payload.error || `Request failed with status ${response.status}`);',
  '        }',
  '',
  '        return payload;',
  '      }',
  '',
  '      function closeEventStream() {',
  '        if (eventSource) {',
  '          eventSource.close();',
  '          eventSource = null;',
  '        }',
  '      }',
  '',
  '      function showLogin(message = "") {',
  '        loginPanel.classList.remove("hidden");',
  '        dashboard.classList.add("hidden");',
  '        closeEventStream();',
  '        if (message) {',
  '          loginMessage.textContent = message;',
  '          loginMessage.className = "banner error";',
  '          loginMessage.classList.remove("hidden");',
  '        } else {',
  '          loginMessage.className = "banner hidden";',
  '          loginMessage.textContent = "";',
  '        }',
  '      }',
  '',
  '      function connectEventStream() {',
  '        closeEventStream();',
  '        eventSource = new EventSource("/api/events");',
  '',
  '        eventSource.addEventListener("status", (event) => {',
  '          try {',
  '            renderStatus(JSON.parse(event.data));',
  '          } catch (error) {',
  '            console.error("Failed to parse status event", error);',
  '          }',
  '        });',
  '',
  '        eventSource.addEventListener("log", (event) => {',
  '          try {',
  '            const entry = JSON.parse(event.data);',
  '            currentLogs = [entry, ...currentLogs.filter((item) => item.id !== entry.id)].slice(0, 200);',
  '            renderLogs();',
  '          } catch (error) {',
  '            console.error("Failed to parse log event", error);',
  '          }',
  '        });',
  '      }',
  '',
  '      function showDashboard() {',
  '        loginPanel.classList.add("hidden");',
  '        dashboard.classList.remove("hidden");',
  '        loginMessage.className = "banner hidden";',
  '        loginMessage.textContent = "";',
  '        if (!eventSource) connectEventStream();',
  '      }',
  '',
  '      function renderTable(headers, rows) {',
  '        if (!rows.length) return `<p class="muted">Nothing to show.</p>`;',
  '        return `',
  '          <table>',
  '            <thead>',
  '              <tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr>',
  '            </thead>',
  '            <tbody>',
  '              ${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("")}',
  '            </tbody>',
  '          </table>',
  '        `;',
  '      }',
  '',
  '      function renderLogs() {',
  '        if (!currentLogs.length) {',
  '          liveLogs.innerHTML = `<p class="muted">No logs yet.</p>`;',
  '          return;',
  '        }',
  '',
  '        liveLogs.innerHTML = `',
  '          <div class="logs">',
  '            ${currentLogs.map((entry) => `',
  '              <div class="log-entry ${escapeHtml(entry.level || "info")}">',
  '                <div class="log-meta">',
  '                  <span>${escapeHtml((entry.level || "info").toUpperCase())}</span>',
  '                  <span>${escapeHtml(new Date(entry.timestamp).toLocaleString())}</span>',
  '                </div>',
  '                <div class="log-message">${escapeHtml(entry.message || "")}</div>',
  '              </div>',
  '            `).join("")}',
  '          </div>',
  '        `;',
  '      }',
  '',
  '      function renderSourceActionButtons(kind, source, options = {}) {',
  '        const encodedKind = encodeURIComponent(kind);',
  '        const encodedSource = encodeURIComponent(source);',
  '        const buttons = [];',
  '        if (options.updateSupported) {',
  '          buttons.push(`<button type="button" class="secondary small" data-resource-action="update" data-kind="${encodedKind}" data-source="${encodedSource}">Update</button>`);',
  '        }',
  '        buttons.push(`<button type="button" class="danger small" data-resource-action="remove" data-kind="${encodedKind}" data-source="${encodedSource}">Remove</button>`);',
  '        return `<div class="source-actions">${buttons.join("")}</div>`;',
  '      }',
  '',
  '      function renderConfiguredSource(title, kind, source, options = {}) {',
  '        const details = [`<div>${code(source)}</div>`];',
  '        if (options.note) details.push(`<div class="small">${escapeHtml(options.note)}</div>`);',
  '        return `',
  '          <div class="item">',
  '            <div class="source-item-header">',
  '              <div>',
  '                <div class="item-title">${escapeHtml(title)}</div>',
  '                <div class="meta">${details.join("")}</div>',
  '              </div>',
  '              ${renderSourceActionButtons(kind, source, options)}',
  '            </div>',
  '          </div>',
  '        `;',
  '      }',
  '',
  '      async function runResourceAction(action, kind, source, button) {',
  '        if (!action || !kind || !source) return;',
  '',
  '        if (action === "remove") {',
  '          const confirmed = window.confirm(`Remove ${kind} source from my-pi?',
  '',
  '${source}`);',
  '          if (!confirmed) return;',
  '        }',
  '',
  '        if (button) button.disabled = true;',
  '        clearBanner();',
  '',
  '        try {',
  '          const endpoint = action === "update" ? "/api/resources/update" : "/api/resources/remove";',
  '          const payload = await api(endpoint, {',
  '            method: "POST",',
  '            body: JSON.stringify({ kind, source }),',
  '          });',
  '          showBanner(payload.message || "Action completed.", "success");',
  '          await loadStatus();',
  '        } catch (error) {',
  '          showBanner(error.message || "Action failed.", "error");',
  '        } finally {',
  '          if (button && button.isConnected) button.disabled = false;',
  '        }',
  '      }',
  '',
  '      function renderStatus(data) {',
  '        const app = data.app;',
  '        const runtime = data.runtime;',
  '        const automations = data.automations;',
  '        const resources = data.resources;',
  '        if (Array.isArray(data.logs)) {',
  '          currentLogs = data.logs;',
  '          renderLogs();',
  '        }',
  '',
  '        statsGrid.innerHTML = [',
  '          ["Channel", app.channelType],',
  '          ["Uptime", formatDuration(app.uptimeSeconds)],',
  '          ["Active sessions", runtime.activeSessions],',
  '          ["Queued chats", runtime.queuedChats],',
  '          ["Queued messages", runtime.totalQueuedMessages],',
  '          ["Cron jobs", automations.cronJobs.length],',
  '          ["Reminders", automations.reminders.length],',
  '          ["Notes", automations.notesCount],',
  '          ["Extensions", resources.extensions.length],',
  '          ["Skills", resources.skills.length],',
  '        ].map(([label, value]) => `',
  '          <div class="stat">',
  '            <div class="label">${escapeHtml(label)}</div>',
  '            <div class="value">${escapeHtml(value)}</div>',
  '          </div>',
  '        `).join("");',
  '',
  '        const sourceItems = [];',
  '        for (const entry of resources.configured.packages) {',
  '          sourceItems.push(renderConfiguredSource("Package source", "package", entry.source, {',
  '            updateSupported: entry.updateSupported,',
  '            note: entry.updateSupported ? "Remote package source — update pulls the latest version/ref." : "Local package source — remove detaches it from my-pi.",',
  '          }));',
  '        }',
  '        for (const entry of resources.configured.extensionPaths) {',
  '          sourceItems.push(renderConfiguredSource("Extension path", "extension-path", entry, {',
  '            note: "Local extension path managed by my-pi.",',
  '          }));',
  '        }',
  '        for (const entry of resources.configured.skillPaths) {',
  '          sourceItems.push(renderConfiguredSource("Skill path", "skill-path", entry, {',
  '            note: "Local skill path managed by my-pi.",',
  '          }));',
  '        }',
  '        configuredSources.innerHTML = sourceItems.length',
  '          ? sourceItems.join("")',
  '          : `<p class="muted">No my-pi scoped package/path sources configured yet.</p>`;',
  '',
  '        activeChats.innerHTML = renderTable(',
  '          ["Chat", "Messages", "Queue", "Idle timer", "Resource gen"],',
  '          runtime.chats.map((chat) => [',
  '            code(chat.chatId),',
  '            escapeHtml(chat.messageCount),',
  '            escapeHtml(chat.queuedMessages),',
  '            chat.hasIdleTimer ? badge("armed", "good") : badge("inactive", "warn"),',
  '            escapeHtml(chat.resourceGeneration),',
  '          ])',
  '        );',
  '',
  '        extensionsTable.innerHTML = renderTable(',
  '          ["Path", "Managed", "Tools", "Commands"],',
  '          resources.extensions.map((extension) => [',
  '            `',
  '              <div><strong>${escapeHtml(extension.sourceInfo.source)}</strong></div>',
  '              <div class="small">${code(extension.resolvedPath)}</div>',
  '              <div class="small">scope=${escapeHtml(extension.sourceInfo.scope)} · origin=${escapeHtml(extension.sourceInfo.origin)}</div>',
  '            `,',
  '            extension.managedByMyPi ? badge("my-pi", "good") : badge("shared", "warn"),',
  '            extension.tools.length ? extension.tools.map((tool) => badge(tool)).join("") : `<span class="muted">—</span>`,',
  '            extension.commands.length ? extension.commands.map((command) => badge(command)).join("") : `<span class="muted">—</span>`,',
  '          ])',
  '        );',
  '',
  '        skillsTable.innerHTML = renderTable(',
  '          ["Skill", "Managed", "Path"],',
  '          resources.skills.map((skill) => [',
  '            `',
  '              <div><strong>${escapeHtml(skill.name)}</strong></div>',
  '              <div class="small">${escapeHtml(skill.description)}</div>',
  '              <div class="small">source=${escapeHtml(skill.sourceInfo.source)}</div>',
  '            `,',
  '            [',
  '              skill.managedByMyPi ? badge("my-pi", "good") : badge("shared", "warn"),',
  '              skill.disableModelInvocation ? badge("manual only", "bad") : badge("auto-load", "good"),',
  '            ].join(""),',
  '            `<div class="small">${code(skill.filePath)}</div>`,',
  '          ])',
  '        );',
  '',
  '        cronJobs.innerHTML = renderTable(',
  '          ["Job", "Schedule", "Status", "Work dir"],',
  '          automations.cronJobs.map((job) => [',
  '            `',
  '              <div><strong>${escapeHtml(job.name)}</strong></div>',
  '              <div class="small">${code(job.id)}</div>',
  '              <div class="small">${escapeHtml(job.task)}</div>',
  '            `,',
  '            code(job.schedule),',
  '            [',
  '              job.enabled ? badge("enabled", "good") : badge("disabled", "warn"),',
  '              job.lastStatus ? badge(job.lastStatus, job.lastStatus === "error" ? "bad" : job.lastStatus === "skipped" ? "warn" : "good") : "",',
  '            ].join(""),',
  '            `<div class="small">${code(job.workDir)}</div>`,',
  '          ])',
  '        );',
  '',
  '        reminders.innerHTML = renderTable(',
  '          ["Reminder", "Chat", "When"],',
  '          automations.reminders.map((reminder) => [',
  '            escapeHtml(reminder.message),',
  '            code(reminder.chatId),',
  '            escapeHtml(new Date(reminder.fireAt).toLocaleString()),',
  '          ])',
  '        );',
  '',
  '        const diagnosticBlocks = [];',
  '        if (resources.extensionErrors.length) {',
  '          diagnosticBlocks.push(`',
  '            <div class="item">',
  '              <div class="item-title">Extension load errors</div>',
  '              <pre>${escapeHtml(resources.extensionErrors.map((entry) => `${entry.path}: ${entry.error}`).join("\\n"))}</pre>',
  '            </div>',
  '          `);',
  '        }',
  '        if (resources.skillDiagnostics.length) {',
  '          diagnosticBlocks.push(`',
  '            <div class="item">',
  '              <div class="item-title">Skill diagnostics</div>',
  '              <pre>${escapeHtml(resources.skillDiagnostics.map((entry) => `${entry.type || "info"}: ${entry.message}${entry.path ? ` (${entry.path})` : ""}`).join("\\n"))}</pre>',
  '            </div>',
  '          `);',
  '        }',
  '        if (resources.promptDiagnostics.length) {',
  '          diagnosticBlocks.push(`',
  '            <div class="item">',
  '              <div class="item-title">Prompt diagnostics</div>',
  '              <pre>${escapeHtml(resources.promptDiagnostics.map((entry) => `${entry.type || "info"}: ${entry.message}${entry.path ? ` (${entry.path})` : ""}`).join("\\n"))}</pre>',
  '            </div>',
  '          `);',
  '        }',
  '        if (resources.settingsErrors.length) {',
  '          diagnosticBlocks.push(`',
  '            <div class="item">',
  '              <div class="item-title">Settings errors</div>',
  '              <pre>${escapeHtml(resources.settingsErrors.join("\\n"))}</pre>',
  '            </div>',
  '          `);',
  '        }',
  '        diagnostics.innerHTML = diagnosticBlocks.length',
  '          ? diagnosticBlocks.join("")',
  '          : `<p class="muted">No current diagnostics.</p>`;',
  '',
  '        appDetails.innerHTML = `',
  '          <div class="list">',
  '            <div class="item">',
  '              <div class="item-title">Service</div>',
  '              <div class="meta">',
  '                <div>Started: ${escapeHtml(new Date(app.startedAt).toLocaleString())}</div>',
  '                <div>PID: ${escapeHtml(app.pid)}</div>',
  '                <div>Node: ${escapeHtml(app.nodeVersion)}</div>',
  '                <div>Channel: ${escapeHtml(app.channelType)}</div>',
  '              </div>',
  '            </div>',
  '            <div class="item">',
  '              <div class="item-title">Paths</div>',
  '              <div class="meta">',
  '                <div>Default work dir: ${code(app.defaultWorkDir)}</div>',
  '                <div>Data dir: ${code(app.dataDir)}</div>',
  '                <div>My-pi agent dir: ${code(app.myPiAgentDir)}</div>',
  '              </div>',
  '            </div>',
  '            <div class="item">',
  '              <div class="item-title">Resource refresh</div>',
  '              <div class="meta">',
  '                <div>Last refreshed: ${escapeHtml(new Date(resources.refreshedAt).toLocaleString())}</div>',
  '                <div>Resource generation: ${escapeHtml(runtime.resourceGeneration)}</div>',
  '              </div>',
  '            </div>',
  '          </div>',
  '        `;',
  '      }',
  '',
  '      async function loadStatus() {',
  '        const payload = await api("/api/status", { method: "GET" });',
  '        showDashboard();',
  '        renderStatus(payload);',
  '      }',
  '',
  '      loginForm.addEventListener("submit", async (event) => {',
  '        event.preventDefault();',
  '        const form = new FormData(loginForm);',
  '        const token = String(form.get("token") || "").trim();',
  '        if (!token) {',
  '          showLogin("Token is required.");',
  '          return;',
  '        }',
  '',
  '        try {',
  '          await api("/api/auth/login", {',
  '            method: "POST",',
  '            body: JSON.stringify({ token }),',
  '          });',
  '          clearBanner();',
  '          await loadStatus();',
  '        } catch (error) {',
  '          showLogin(error.message || "Login failed.");',
  '        }',
  '      });',
  '',
  '      installForm.addEventListener("submit", async (event) => {',
  '        event.preventDefault();',
  '        installButton.disabled = true;',
  '        const form = new FormData(installForm);',
  '        const kind = String(form.get("kind") || "package");',
  '        const source = String(form.get("source") || "").trim();',
  '        clearBanner();',
  '        try {',
  '          const payload = await api("/api/install", {',
  '            method: "POST",',
  '            body: JSON.stringify({ kind, source }),',
  '          });',
  '          showBanner(payload.message || "Installed successfully.", "success");',
  '          await loadStatus();',
  '          installForm.reset();',
  '          document.getElementById("install-kind").value = kind;',
  '        } catch (error) {',
  '          showBanner(error.message || "Install failed.", "error");',
  '        } finally {',
  '          installButton.disabled = false;',
  '        }',
  '      });',
  '',
  '      configuredSources.addEventListener("click", (event) => {',
  '        const target = event.target;',
  '        if (!(target instanceof Element)) return;',
  '        const button = target.closest("button[data-resource-action]");',
  '        if (!button) return;',
  '',
  '        const action = button.getAttribute("data-resource-action") || "";',
  '        const kind = decodeURIComponent(button.getAttribute("data-kind") || "");',
  '        const source = decodeURIComponent(button.getAttribute("data-source") || "");',
  '        void runResourceAction(action, kind, source, button);',
  '      });',
  '',
  '      refreshButton.addEventListener("click", () => {',
  '        clearBanner();',
  '        loadStatus().catch((error) => showBanner(error.message || "Refresh failed.", "error"));',
  '      });',
  '',
  '      reloadResourcesButton.addEventListener("click", async () => {',
  '        reloadResourcesButton.disabled = true;',
  '        clearBanner();',
  '        try {',
  '          const payload = await api("/api/resources/reload", { method: "POST", body: JSON.stringify({}) });',
  '          showBanner(payload.message || "Resources reloaded.", "success");',
  '          await loadStatus();',
  '        } catch (error) {',
  '          showBanner(error.message || "Reload failed.", "error");',
  '        } finally {',
  '          reloadResourcesButton.disabled = false;',
  '        }',
  '      });',
  '',
  '      logoutButton.addEventListener("click", async () => {',
  '        closeEventStream();',
  '        await fetch("/api/auth/logout", { method: "POST" }).catch(() => {});',
  '        showLogin();',
  '      });',
  '',
  '      loadStatus().catch(() => showLogin());',
  '    </script>',
  '  </body>',
  '</html>',
];

export function buildDashboardHtml(): string {
  return DASHBOARD_HTML_LINES.join("\n");
}
